using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace SudokuSolver
{
    [Serializable]
    public class sudokuGrid
    {
        public int square_1 { get; set; } = 0;
        public int square_2 { get; set; } = 0;
        public int square_3 { get; set; } = 0;
        public int square_4 { get; set; } = 0;
        public int square_5 { get; set; } = 0;
        public int square_6 { get; set; } = 0;
        public int square_7 { get; set; } = 0;
        public int square_8 { get; set; } = 0;
        public int square_9 { get; set; } = 0;
        public int square_10 { get; set; } = 0;
        public int square_11 { get; set; } = 0;
        public int square_12 { get; set; } = 0;
        public int square_13 { get; set; } = 0;
        public int square_14 { get; set; } = 0;
        public int square_15 { get; set; } = 0;
        public int square_16 { get; set; } = 0;
        public int square_17 { get; set; } = 0;
        public int square_18 { get; set; } = 0;
        public int square_19 { get; set; } = 0;
        public int square_20 { get; set; } = 0;
        public int square_21 { get; set; } = 0;
        public int square_22 { get; set; } = 0;
        public int square_23 { get; set; } = 0;
        public int square_24 { get; set; } = 0;
        public int square_25 { get; set; } = 0;
        public int square_26 { get; set; } = 0;
        public int square_27 { get; set; } = 0;
        public int square_28 { get; set; } = 0;
        public int square_29 { get; set; } = 0;
        public int square_30 { get; set; } = 0;
        public int square_31 { get; set; } = 0;
        public int square_32 { get; set; } = 0;
        public int square_33 { get; set; } = 0;
        public int square_34 { get; set; } = 0;
        public int square_35 { get; set; } = 0;
        public int square_36 { get; set; } = 0;
        public int square_37 { get; set; } = 0;
        public int square_38 { get; set; } = 0;
        public int square_39 { get; set; } = 0;
        public int square_40 { get; set; } = 0;
        public int square_41 { get; set; } = 0;
        public int square_42 { get; set; } = 0;
        public int square_43 { get; set; } = 0;
        public int square_44 { get; set; } = 0;
        public int square_45 { get; set; } = 0;
        public int square_46 { get; set; } = 0;
        public int square_47 { get; set; } = 0;
        public int square_48 { get; set; } = 0;
        public int square_49 { get; set; } = 0;
        public int square_50 { get; set; } = 0;
        public int square_51 { get; set; } = 0;
        public int square_52 { get; set; } = 0;
        public int square_53 { get; set; } = 0;
        public int square_54 { get; set; } = 0;
        public int square_55 { get; set; } = 0;
        public int square_56 { get; set; } = 0;
        public int square_57 { get; set; } = 0;
        public int square_58 { get; set; } = 0;
        public int square_59 { get; set; } = 0;
        public int square_60 { get; set; } = 0;
        public int square_61 { get; set; } = 0;
        public int square_62 { get; set; } = 0;
        public int square_63 { get; set; } = 0;
        public int square_64 { get; set; } = 0;
        public int square_65 { get; set; } = 0;
        public int square_66 { get; set; } = 0;
        public int square_67 { get; set; } = 0;
        public int square_68 { get; set; } = 0;
        public int square_69 { get; set; } = 0;
        public int square_70 { get; set; } = 0;
        public int square_71 { get; set; } = 0;
        public int square_72 { get; set; } = 0;
        public int square_73 { get; set; } = 0;
        public int square_74 { get; set; } = 0;
        public int square_75 { get; set; } = 0;
        public int square_76 { get; set; } = 0;
        public int square_77 { get; set; } = 0;
        public int square_78 { get; set; } = 0;
        public int square_79 { get; set; } = 0;
        public int square_80 { get; set; } = 0;
        public int square_81 { get; set; } = 0;
    }
}
